### ISSUE TITLE
Other platforms

### ISSUE THREAD

**Issue by Rundik** [stefansl/image-shrinker#40]
Why isn't this app available for other platforms (linux/windows)? It was made using electron, so it can be cross platform

**Comment by stefansl** [comment]
I know, but I don't want to install wine or a virtual box on my mac. A pull request would be nice  :)

**Comment by jancborchardt** [comment]
@stefansl I’m using Ubuntu 17.10 and am happy to help building this app as it’s suuuper useful for me. :) (Thanks for supporting png _and_ also svg!)

The `npm run pack-linux` runs and the app works nicely. How can I contribute the build – do I submit a zip of what’s in the folder `Image Shrinker-linux-x64` somewhere?

**Comment by stefansl** [comment]
@jancborchardt nice! i never expected, that it will run without additional coding. i could add you as maintainer, if want. then you could add the file here: 
https://github.com/stefansl/image-shrinker/releases

**Comment by jancborchardt** [comment]
@stefansl hehe, at least it does seem to work from initial testing. :) And sure, am happy to be added & to add the Linux releases.

**Comment by Rundik** [comment]
@jancborchardt oh, I didn't know it's so easy to compile, didn't read the readme xD

**Comment by jancborchardt** [comment]
@stefansl sorry for the delay! :) I’m looking into it again, but I discovered an issue while using it regarding the loss-amount of the compression: https://github.com/stefansl/image-shrinker/issues/42

**Comment by jancborchardt** [comment]
@stefansl built with latest master and uploaded the zipped build in the release, also adjusted the release title and content accordingly. :) https://github.com/stefansl/image-shrinker/releases/tag/v1.3.6

This is what’s generated, and showing that it’s working:
![screenshot from 2018-05-31 04-00-59](https://user-images.githubusercontent.com/925062/40757327-3a88393c-6488-11e8-9691-61723d82827d.png)

The terminal just shows that of course when you move the main executable it will not work. Is there a way we can achieve a packaged file? Will look into if it’s possible to build a .deb file somehow.

**Comment by jancborchardt** [comment]
There seems to be https://github.com/unindented/electron-installer-debian for just that. Am trying that out now.

**Comment by stefansl** [comment]
@jancborchardt Thank you very much! Nice work! I guess we just have to adjust the package.json in the section "build" and we need some new top-level-sections, eg. "deb", "rpm", "appImage"
We can use electron-builder, then. See the doku here: https://www.electron.build/configuration/linux

checkout https://www.electron.build/cli as well. or try electron-builder --help

you can see, how I'm building it in the package.json here: https://github.com/stefansl/image-shrinker/blob/176b7b6cebcd702f2f88d9cf531f9b1bc01cdb06/package.json#L31

maybe I've to adjust it to build-mac: "electron-builder --publish always --mac"

**Comment by derpmarine168** [comment]
i'd rather like it for windows, so i'm gonna build it for myself. do you want a copy to put in releases? 😉

**Comment by derpmarine168** [comment]
my build has been successful using `npm install&&electron-packager . Image-Shrinker --asar=true --platform=win32 --arch=ia32 --ignore=/^release/i --overwrite`! 🎉 

![image](https://user-images.githubusercontent.com/28905212/42844008-a5aa5f50-8a09-11e8-92b1-dd6ba06a1849.png)

unfortunately using electron-packager . 'Image Shrinker'  means that the created executable is called _'image_, strangely.

**Comment by derpmarine168** [comment]
with some changes, I've managed to fix the icon issue and remove the _(ugly)_ top menu.

![image](https://user-images.githubusercontent.com/28905212/42892701-5d774d96-8aaa-11e8-9727-8dc94990ffda.png)

should i launch a PR with my changes?

**Comment by derpmarine168** [comment]
i'm also wondering about using [`electron-installer-windows`](https://www.npmjs.com/package/electron-installer-windows) to create a installer?

**Comment by derpmarine168** [comment]
working on it.

**Comment by derpmarine168** [comment]
if my internet goes above 20KiB/2. 😉

**Comment by derpmarine168** [comment]
sorry it's been taking so long. I've had to leave to do some other stuff, and now i'm done my git's died.

    >git clone https://github.com/stefansl/image-shrinker.git
   Cloning into 'image-shrinker'...
    fatal: unable to access 'https://github.com/stefansl/image-shrinker.git/': error setting certificate verify 
    locations:
      CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none

**Comment by jancborchardt** [comment]
@derpmarine168 maybe this helps? :) https://stackoverflow.com/questions/3778042/github-error-cloning-my-private-repository

**Comment by despecial** [comment]
@JoelEllis did you release the window version anywhere? Thanks for the effort!

**Comment by JoelEllis** [comment]
@despecial I did release a build on my fork, but it is now 52 commits behind, however I think you can build it yourself from master now.

**Comment by despecial** [comment]
@JoelEllis thanks, I dont have a windows machine - not sure if I can build it on a mac?!
It's for my friends, they use MS.

**Comment by stefansl** [comment]
@despecial I think you have to use a virtual
Machine with Windows installed. That’s why I don’t build the Win version

**Comment by stefansl** [comment]
With electron-builder it's possible to create versions for all platforms easily. I have to test this and I'm planing to remove electron-packer, because it's deprecated.

**Comment by stefansl** [comment]
see https://github.com/stefansl/image-shrinker/issues/56
