### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by derpmarine168** [stefansl/image-shrinker#48]
wondering  about getting support for gifs. I've done it with gifsicle here: <https://github.com/stefansl/image-shrinker/pull/47> but any other ideas?

**Comment by stefansl** [comment]
Sorry for the delay ... I will check it soon. Does gifsicle work with animated gifs as well?

**Comment by derpmarine168** [comment]
yep!

**Comment by derpmarine168** [comment]
i actually used this fork to get the GIF in <https://github.com/stefansl/image-shrinker/pull/44#issuecomment-408083171>

**Comment by stefansl** [comment]
I guess it was a problem with animated gifs. Did it work with gifsicle?

**Comment by derpmarine168** [comment]
did what work with gifsicle? everything I've tried has worked on my windows pc.

**Comment by stefansl** [comment]
Nice one. Works like charm, thx!
