### ISSUE TITLE
Typo on the website.

### ISSUE THREAD

**Issue by MatyasKriz** [stefansl/image-shrinker#49]
Hey, I found a typo on the website https://image-shrinker.com/ in the word "immediately" ("Immediatly!").

Now, I know grammar nazis are not liked very much on the internet, but if it's not on purpose (some pun I missed?) and you didn't know about it, I just wanted to let you know.

Have a good one!

Source: https://www.thesaurus.com/browse/immediately

**Comment by stefansl** [comment]
Thanks :) and good to to know! I fixed it ...
