### ISSUE TITLE
Spelling mistake: Image "shrinked"...should be "shrunk"/"shrunken"

### ISSUE THREAD

**Issue by nemitia** [stefansl/image-shrinker#60]
Hey there, did not use the app. Just noticed in your slideshow the above mentioned spelling mistake. For your convenience check out the conjugation of the verb shrink here:
https://conjugator.reverso.net/conjugation-english-verb-shrink.html

Cheers, Martin

**Comment by stefansl** [comment]
Thanks for the hint! :)
