### ISSUE TITLE
Settings are ignored / 1.6.2

### ISSUE THREAD

**Issue by jschmdt** [stefansl/image-shrinker#61]
Hey Stefan,
First of all, thanks for your great app! :D 

As I downloaded the latest Version of Image Shrinker to minify my website images I now have discovered an issue, which I can't get solved, even after a clean install of the app.

Issue:
Settings in the "Preferences" are ignored.
"Minified" folder is created after I drag and drop my JPGs on "Image Shrinker".
Also a ".min suffix" is added to all the files.

My settings:
- "Save shrinked files in same folder = activated
- "Add .min suffix" = deactivated
- "Add subfolder "minified"" = deactivated

OS: macOS High Sierra – 10.13.6

![image_shrinker-settings](https://user-images.githubusercontent.com/36086898/95662011-32989f00-0b34-11eb-87a2-454c9cabb042.png)

**Comment by stefansl** [comment]
Thx for the report! I'm uploading a fix right now.

**Comment by stefansl** [comment]
Fixed in 7c7402cd82e4e546d5d8cd921e7d9a2f09aacaae
